# Generated by Django 5.1.5 on 2026-03-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RunActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strava_id', models.CharField(help_text='来自 Strava API 的活动唯一标识符', max_length=64, unique=True, verbose_name='Strava 活动 ID')),
                ('name', models.CharField(max_length=255, verbose_name='活动名称')),
                ('date', models.DateTimeField(verbose_name='运动日期')),
                ('distance_km', models.FloatField(verbose_name='距离（公里）')),
                ('moving_time_min', models.FloatField(verbose_name='移动时间（分钟）')),
                ('average_heart_rate', models.FloatField(blank=True, help_text='未佩戴心率设备时为空', null=True, verbose_name='平均心率（bpm）')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='最后同步时间')),
            ],
            options={
                'verbose_name': '跑步活动',
                'verbose_name_plural': '跑步活动',
                'ordering': ['-date'],
            },
        ),
    ]
